freeze: false

model:
  vehicle:
    fusion_model:
      type: BEVFusionHeadless
      encoders: null
      fuser: null
  infrastructure:
    fusion_model:
      type: BEVFusionHeadless
      encoders: null
      fuser: null
  coop_fuser:
    type: MaxFuser
    in_channels: [80, 80]
    out_channels: 80
