model:
  vehicle:
    fusion_model:
      fuser:
        type: ConvFuser
        in_channels: [80, 256]
        out_channels: 256
  infrastructure:
    fusion_model:
      fuser:
        type: ConvFuser
        in_channels: [80, 256]
        out_channels: 256

data:
  samples_per_gpu: 2

optimizer_config:
  cumulative_iters: 2

