augment3d:
  scale: [0.95, 1.05]
  rotate: [-0.3925, 0.3925]
  translate: 0

model:
  vehicle:
    fusion_model:
      encoders:
        lidar: null
        camera:
          vtransform:
            type: CoopVehicleLSSTransform
            image_size: ${image_size}
            xbound: [-75.0, 75.0, 0.8]
            ybound: [-75.0, 75.0, 0.8]
            zbound: [-10.0, 10.0, 20.0]
            dbound: [1.0, 60.0, 1.0]
            vehicle: true
  heads:
    object:
      test_cfg:
        nms_type:
          - circle
          - rotate
          - rotate
          - circle
          - rotate
          - rotate
        nms_scale:
          - [1.0]
          - [1.0, 1.0]
          - [1.0, 1.0]
          - [1.0]
          - [1.0, 1.0]
          - [2.5, 4.0]

lr_config: null
