#!/usr/bin/env python3
"""Train one controlled cooperative baseline on the sealed training overlays."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import keyword
import os
import pprint
import re
import sys
from collections.abc import Mapping
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.resilient_v2x.evaluate_controlled_baselines import (  # noqa: E402
    ControlledBaselineEvaluationError as _EvaluationError,
    _atomic_json,
    _atomic_write,
    _load_json_mapping,
    _load_python_config,
    _mapping,
    _overlay_descriptor,
    _sha256_file,
    _verify_content_hash,
)
from transvision.dataset.resilient_v2x_manifest import (  # noqa: E402
    content_sha256,
)


BASELINE_CONFIG_DIR = ROOT / "configs" / "resilient_v2x" / "baselines"
DEFAULT_TRAINING_INDEX = (
    ROOT / "artifacts" / "resilient_v2x" / "dair_v2" / "training_overlays.json"
)
DEFAULT_SEED = 20250218
TRAINING_INDEX_TYPE = "resilient_v2x_training_overlays"
SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")


def _discover_baseline_configs() -> dict[str, Path]:
    """Discover leaf configs so a future ``ffnet.py`` needs no CLI edit."""

    return {
        path.stem: path.resolve()
        for path in sorted(BASELINE_CONFIG_DIR.glob("*.py"))
        if not path.name.startswith("_")
    }


BASELINE_CONFIGS = _discover_baseline_configs()
BASELINES = tuple(BASELINE_CONFIGS)


class ControlledBaselineTrainingError(ValueError):
    """Raised when a controlled training run cannot be resolved safely."""


def _sha256(value: object, context: str) -> str:
    if type(value) is not str or SHA256_PATTERN.fullmatch(value) is None:
        raise ControlledBaselineTrainingError(
            f"{context} must be lowercase hexadecimal SHA-256"
        )
    return value


def _seed(value: object) -> int:
    if type(value) is not int or value < 0:
        raise ControlledBaselineTrainingError("seed must be a non-negative integer")
    return value


def _render_config(config: Mapping[str, object]) -> bytes:
    lines = [
        "# Generated by tools/resilient_v2x/train_controlled_baseline.py.",
        "# Do not edit: regenerate from the baseline and training overlay index.",
        "",
    ]
    for key in sorted(config):
        if not key.isidentifier() or keyword.iskeyword(key):
            raise ControlledBaselineTrainingError(
                f"config key cannot be rendered as Python: {key!r}"
            )
        rendered = pprint.pformat(config[key], width=88, sort_dicts=False)
        lines.extend((f"{key} = {rendered}", ""))
    return ("\n".join(lines) + "\n").encode("utf-8")


def _resolved_config_identity_sha256(config: Mapping[str, object]) -> str:
    """Hash a resolved config while allowing only the resume-state transition."""

    stable = copy.deepcopy(dict(config))
    stable["resume"] = False
    provenance = stable.get("controlled_baseline_training")
    if isinstance(provenance, dict):
        provenance["resume"] = False
    return hashlib.sha256(_render_config(stable)).hexdigest()


def _training_overlay(
    overlays: Mapping[str, object],
    *,
    name: str,
    index_dir: Path,
) -> tuple[Path, str, dict[str, object]]:
    descriptor = _mapping(overlays.get(name), f"overlays.{name}")
    path, uncompressed_sha256 = _overlay_descriptor(
        {"overlay": descriptor},
        index_dir,
        f"overlays.{name}",
    )
    uncompressed_size = descriptor.get("uncompressed_size")
    if uncompressed_size is not None and (
        type(uncompressed_size) is not int or uncompressed_size < 0
    ):
        raise ControlledBaselineTrainingError(
            f"overlays.{name}.uncompressed_size must be a non-negative integer"
        )
    return path, uncompressed_sha256, descriptor


def _forbidden_model_fields(model: Mapping[str, object]) -> tuple[str, ...]:
    forbidden: list[str] = []

    def visit(value: object, path: str) -> None:
        if isinstance(value, Mapping):
            for raw_key, item in value.items():
                key = str(raw_key)
                lowered = key.lower()
                tokens = tuple(
                    token for token in re.split(r"[^a-z0-9]+", lowered) if token
                )
                if (
                    "teacher" in lowered
                    or "ptf" in lowered
                    or "repair" in lowered
                    or "der" in tokens
                    or lowered
                    in {
                        "distillation",
                        "routing_mode",
                        "use_reliability",
                        "use_delay_metadata",
                    }
                ):
                    forbidden.append(f"{path}.{key}")
                visit(item, f"{path}.{key}")
        elif isinstance(value, (list, tuple)):
            for index, item in enumerate(value):
                visit(item, f"{path}[{index}]")

    visit(model, "model")
    return tuple(forbidden)


def _validate_baseline_model(
    model: Mapping[str, object],
    baseline: str,
) -> None:
    if model.get("type") != "ControlledCooperativeBaselineNet":
        raise ControlledBaselineTrainingError(
            "baseline config does not use ControlledCooperativeBaselineNet"
        )
    if model.get("baseline_name") != baseline:
        raise ControlledBaselineTrainingError("baseline config name mismatch")
    forbidden = _forbidden_model_fields(model)
    if forbidden:
        raise ControlledBaselineTrainingError(
            "controlled baseline model contains forbidden "
            f"teacher/PTF/repair/DER fields: {', '.join(forbidden)}"
        )


def _seed_sampler_tree(value: object, seed: int) -> None:
    if isinstance(value, dict):
        for key, item in value.items():
            if key in {"sampler", "batch_sampler"} and isinstance(item, dict):
                item["seed"] = seed
            _seed_sampler_tree(item, seed)
    elif isinstance(value, (list, tuple)):
        for item in value:
            _seed_sampler_tree(item, seed)


def _resolved_training_config(
    source: Mapping[str, object],
    *,
    baseline: str,
    manifest_path: Path,
    data_root: Path,
    expected_split_hash: str,
    transport_path: Path,
    transport_sha256: str,
    fault_path: Path,
    fault_sha256: str,
    training_index: Path,
    training_index_sha256: str,
    work_dir: Path,
    seed: int,
    resume: bool,
) -> dict[str, object]:
    resolved = copy.deepcopy(dict(source))
    model = _mapping(resolved.get("model"), "model")
    _validate_baseline_model(model, baseline)
    resolved["model"] = model
    resolved["work_dir"] = str(work_dir)
    resolved["launcher"] = "none"
    resolved["resume"] = resume

    randomness = _mapping(resolved.get("randomness"), "randomness")
    randomness["seed"] = seed
    resolved["randomness"] = randomness

    for dataloader_name in (
        "train_dataloader",
        "val_dataloader",
        "test_dataloader",
    ):
        dataloader = _mapping(
            resolved.get(dataloader_name),
            dataloader_name,
        )
        dataset = _mapping(
            dataloader.get("dataset"),
            f"{dataloader_name}.dataset",
        )
        dataset["manifest_path"] = str(manifest_path)
        dataset["data_root"] = str(data_root)
        dataset["expected_split_hash"] = expected_split_hash
        dataset["seed"] = seed
        dataset["include_clean_teacher"] = False
        if dataloader_name == "train_dataloader":
            dataset.update(
                transport_overlay_path=str(transport_path),
                transport_overlay_sha256=transport_sha256,
                fault_overlay_path=str(fault_path),
                fault_overlay_sha256=fault_sha256,
            )
        else:
            dataset.update(
                transport_overlay_path=None,
                transport_overlay_sha256=None,
                fault_overlay_path=None,
                fault_overlay_sha256=None,
            )
        dataloader["dataset"] = dataset
        _seed_sampler_tree(dataloader, seed)
        resolved[dataloader_name] = dataloader

    implementation = resolved.get("implementation_choices_dataset")
    if isinstance(implementation, dict) and "global_seed" in implementation:
        implementation["global_seed"] = seed

    resolved["controlled_baseline_training"] = {
        "baseline": baseline,
        "seed": seed,
        "manifest_path": str(manifest_path),
        "data_root": str(data_root),
        "expected_split_hash": expected_split_hash,
        "training_index": str(training_index),
        "training_index_content_sha256": training_index_sha256,
        "transport_overlay_path": str(transport_path),
        "transport_overlay_sha256": transport_sha256,
        "fault_overlay_path": str(fault_path),
        "fault_overlay_sha256": fault_sha256,
        "include_clean_teacher": False,
        "resume": resume,
    }
    return resolved


def _stale_training_artifacts(work_dir: Path) -> tuple[Path, ...]:
    if not work_dir.exists():
        return ()
    stale: list[Path] = []
    for path in work_dir.rglob("*"):
        if not path.is_file():
            continue
        if path.name == "last_checkpoint" or path.suffix.lower() in {
            ".pth",
            ".pt",
            ".ckpt",
            ".log",
        }:
            stale.append(path.resolve())
    return tuple(sorted(stale))


def _verify_planned_overlay(
    plan: Mapping[str, object],
    *,
    prefix: str,
) -> None:
    context = f"{prefix} overlay"
    try:
        path = Path(str(plan[f"{prefix}_overlay"])).resolve(strict=True)
    except (KeyError, OSError) as error:
        raise ControlledBaselineTrainingError(
            f"unable to resolve planned {context}: {error}"
        ) from error
    if not path.is_file():
        raise ControlledBaselineTrainingError(f"planned {context} must be a file")
    size = plan.get(f"{prefix}_overlay_compressed_size")
    if type(size) is not int or size < 0:
        raise ControlledBaselineTrainingError(
            f"plan.{prefix}_overlay_compressed_size must be non-negative"
        )
    if path.stat().st_size != size:
        raise ControlledBaselineTrainingError(
            f"{context} compressed size changed after planning"
        )
    compressed_sha256 = _sha256(
        plan.get(f"{prefix}_overlay_compressed_sha256"),
        f"plan.{prefix}_overlay_compressed_sha256",
    )
    if _sha256_file(path, context) != compressed_sha256:
        raise ControlledBaselineTrainingError(
            f"{context} compressed SHA-256 changed after planning"
        )
    expected_uncompressed = _sha256(
        plan.get(f"{prefix}_overlay_uncompressed_sha256"),
        f"plan.{prefix}_overlay_uncompressed_sha256",
    )
    try:
        import zstandard
    except ImportError as error:
        raise ControlledBaselineTrainingError(
            "overlay verification requires the locked zstandard runtime"
        ) from error

    try:
        digest = hashlib.sha256()
        with path.open("rb") as source:
            with zstandard.ZstdDecompressor().stream_reader(source) as stream:
                for block in iter(lambda: stream.read(1024 * 1024), b""):
                    digest.update(block)
    except (OSError, zstandard.ZstdError) as error:
        raise ControlledBaselineTrainingError(
            f"unable to decompress planned {context}: {error}"
        ) from error
    if digest.hexdigest() != expected_uncompressed:
        raise ControlledBaselineTrainingError(
            f"{context} uncompressed SHA-256 mismatch"
        )


_PLAN_IDENTITY_FIELDS = (
    "schema_version",
    "plan_type",
    "baseline",
    "baseline_config",
    "baseline_config_sha256",
    "baseline_effective_config_sha256",
    "resolved_config",
    "resolved_config_identity_sha256",
    "manifest",
    "manifest_content_sha256",
    "manifest_file_sha256",
    "data_root",
    "expected_split_hash",
    "training_index",
    "training_index_content_sha256",
    "training_index_file_sha256",
    "transport_overlay",
    "transport_overlay_compressed_sha256",
    "transport_overlay_compressed_size",
    "transport_overlay_uncompressed_sha256",
    "fault_overlay",
    "fault_overlay_compressed_sha256",
    "fault_overlay_compressed_size",
    "fault_overlay_uncompressed_sha256",
    "seed",
    "work_dir",
)


def _plan_identity(plan: Mapping[str, object]) -> dict[str, object]:
    try:
        return {key: plan[key] for key in _PLAN_IDENTITY_FIELDS}
    except KeyError as error:
        raise ControlledBaselineTrainingError(
            f"existing training plan lacks identity field: {error.args[0]}"
        ) from error


def _build_training_plan(
    *,
    baseline: str,
    training_index: Path,
    work_dir: Path,
    seed: int,
    resume: bool,
) -> dict[str, object]:
    if baseline not in BASELINE_CONFIGS:
        raise ControlledBaselineTrainingError(f"unsupported baseline: {baseline}")
    normalized_seed = _seed(seed)
    if type(resume) is not bool:
        raise ControlledBaselineTrainingError("resume must be boolean")

    data_root_value = os.environ.get("RESILIENT_V2X_DATA_ROOT")
    if not data_root_value:
        raise ControlledBaselineTrainingError(
            "RESILIENT_V2X_DATA_ROOT must name the prepared dataset directory"
        )
    try:
        data_root = Path(data_root_value).expanduser().resolve(strict=True)
    except OSError as error:
        raise ControlledBaselineTrainingError(
            f"unable to resolve RESILIENT_V2X_DATA_ROOT: {error}"
        ) from error
    if not data_root.is_dir():
        raise ControlledBaselineTrainingError(
            "RESILIENT_V2X_DATA_ROOT must name a directory"
        )
    expected_split_hash = _sha256(
        os.environ.get("RESILIENT_V2X_SPLIT_SHA256"),
        "RESILIENT_V2X_SPLIT_SHA256",
    )
    manifest_value = os.environ.get("RESILIENT_V2X_MANIFEST")
    if not manifest_value:
        raise ControlledBaselineTrainingError(
            "RESILIENT_V2X_MANIFEST must name the temporal manifest JSON"
        )
    manifest_path, manifest = _load_json_mapping(
        Path(manifest_value),
        "RESILIENT_V2X_MANIFEST",
    )
    manifest_digest = _verify_content_hash(manifest, "temporal manifest")
    manifest_file_digest = _sha256_file(manifest_path, "temporal manifest")
    manifest_split_hash = _sha256(
        manifest.get("split_sha256"),
        "temporal manifest.split_sha256",
    )
    if expected_split_hash != manifest_split_hash:
        raise ControlledBaselineTrainingError(
            "RESILIENT_V2X_SPLIT_SHA256 does not match temporal manifest"
        )

    index_path, index = _load_json_mapping(
        Path(training_index),
        "training overlay index",
    )
    if index.get("artifact_type") != TRAINING_INDEX_TYPE:
        raise ControlledBaselineTrainingError(
            f"training overlay index artifact_type must be {TRAINING_INDEX_TYPE!r}"
        )
    index_digest = _verify_content_hash(index, "training overlay index")
    index_file_digest = _sha256_file(index_path, "training overlay index")
    indexed_manifest_digest = _sha256(
        index.get("temporal_manifest_sha256"),
        "training overlay index.temporal_manifest_sha256",
    )
    if indexed_manifest_digest != manifest_digest:
        raise ControlledBaselineTrainingError(
            "training overlay index temporal manifest content hash does not "
            "match RESILIENT_V2X_MANIFEST"
        )
    if index.get("split") != "train":
        raise ControlledBaselineTrainingError(
            "training overlay index split must be 'train'"
        )

    overlays = _mapping(index.get("overlays"), "training overlay index.overlays")
    (
        transport_path,
        transport_digest,
        transport_descriptor,
    ) = _training_overlay(
        overlays,
        name="transport",
        index_dir=index_path.parent,
    )
    fault_path, fault_digest, fault_descriptor = _training_overlay(
        overlays,
        name="fault",
        index_dir=index_path.parent,
    )

    baseline_config_path = BASELINE_CONFIGS[baseline]
    baseline_config = _load_python_config(baseline_config_path)
    baseline_config_digest = _sha256_file(
        baseline_config_path,
        "baseline config",
    )
    baseline_effective_digest = hashlib.sha256(
        _render_config(baseline_config)
    ).hexdigest()
    output_dir = Path(work_dir).expanduser().resolve()
    plan_path = (output_dir / "training_plan.json").resolve()
    stale = _stale_training_artifacts(output_dir)
    if stale and not resume:
        rendered = ", ".join(str(path) for path in stale[:3])
        suffix = "" if len(stale) <= 3 else f" (+{len(stale) - 3} more)"
        raise ControlledBaselineTrainingError(
            "work_dir contains checkpoint/log artifacts; use --resume or a "
            f"fresh directory: {rendered}{suffix}"
        )
    if stale and resume and not plan_path.is_file():
        raise ControlledBaselineTrainingError(
            "refusing to resume checkpoint/log artifacts without an existing "
            "sealed training_plan.json"
        )

    resolved = _resolved_training_config(
        baseline_config,
        baseline=baseline,
        manifest_path=manifest_path,
        data_root=data_root,
        expected_split_hash=expected_split_hash,
        transport_path=transport_path,
        transport_sha256=transport_digest,
        fault_path=fault_path,
        fault_sha256=fault_digest,
        training_index=index_path,
        training_index_sha256=index_digest,
        work_dir=output_dir,
        seed=normalized_seed,
        resume=resume,
    )
    resolved_raw = _render_config(resolved)
    resolved_digest = hashlib.sha256(resolved_raw).hexdigest()
    resolved_path = (output_dir / "resolved_config.py").resolve()
    resolved_identity_digest = _resolved_config_identity_sha256(resolved)
    plan: dict[str, object] = {
        "schema_version": 1,
        "plan_type": "resilient_v2x_controlled_baseline_training",
        "baseline": baseline,
        "baseline_config": str(baseline_config_path),
        "baseline_config_sha256": baseline_config_digest,
        "resolved_config": str(resolved_path),
        "resolved_config_sha256": resolved_digest,
        "manifest": str(manifest_path),
        "baseline_effective_config_sha256": baseline_effective_digest,
        "manifest_content_sha256": manifest_digest,
        "manifest_file_sha256": manifest_file_digest,
        "resolved_config_identity_sha256": resolved_identity_digest,
        "data_root": str(data_root),
        "expected_split_hash": expected_split_hash,
        "training_index": str(index_path),
        "training_index_content_sha256": index_digest,
        "training_index_file_sha256": index_file_digest,
        "training_index_protocol_seed": index.get("protocol_seed"),
        "transport_overlay": str(transport_path),
        "transport_overlay_compressed_sha256": transport_descriptor[
            "compressed_sha256"
        ],
        "transport_overlay_compressed_size": transport_descriptor["compressed_size"],
        "transport_overlay_uncompressed_sha256": transport_digest,
        "fault_overlay": str(fault_path),
        "fault_overlay_compressed_sha256": fault_descriptor["compressed_sha256"],
        "fault_overlay_compressed_size": fault_descriptor["compressed_size"],
        "fault_overlay_uncompressed_sha256": fault_digest,
        "seed": normalized_seed,
        "resume": resume,
        "work_dir": str(output_dir),
        "plan_path": str(plan_path),
    }

    if resume and plan_path.exists():
        _, existing = _load_json_mapping(plan_path, "existing training plan")
        _verify_content_hash(existing, "existing training plan")
        if _plan_identity(existing) != _plan_identity(plan):
            raise ControlledBaselineTrainingError(
                "refusing to overwrite a different training plan while resuming"
            )
        existing_resolved_value = existing.get("resolved_config")
        if type(existing_resolved_value) is not str or not existing_resolved_value:
            raise ControlledBaselineTrainingError(
                "existing training plan has no resolved config path"
            )
        try:
            existing_resolved = Path(existing_resolved_value).resolve(strict=True)
        except OSError as error:
            raise ControlledBaselineTrainingError(
                f"unable to resolve existing resolved config: {error}"
            ) from error
        existing_resolved_digest = _sha256(
            existing.get("resolved_config_sha256"),
            "existing training plan.resolved_config_sha256",
        )
        if (
            _sha256_file(existing_resolved, "existing resolved config")
            != existing_resolved_digest
        ):
            raise ControlledBaselineTrainingError(
                "existing resolved config changed after its training plan was sealed"
            )

    output_dir.mkdir(parents=True, exist_ok=True)
    _atomic_write(resolved_path, resolved_raw)
    plan["content_sha256"] = content_sha256(plan)
    _atomic_json(plan_path, plan)
    return plan


def build_training_plan(
    *,
    baseline: str,
    work_dir: Path,
    training_index: Path = DEFAULT_TRAINING_INDEX,
    seed: int = DEFAULT_SEED,
    resume: bool = False,
) -> dict[str, object]:
    """Resolve, validate, and atomically publish one baseline training plan."""

    try:
        return _build_training_plan(
            baseline=baseline,
            training_index=training_index,
            work_dir=work_dir,
            seed=seed,
            resume=resume,
        )
    except _EvaluationError as error:
        raise ControlledBaselineTrainingError(str(error)) from error


def execute_training_plan(plan: Mapping[str, object]) -> object:
    """Verify the sealed inputs again, construct MMEngine Runner, and train."""

    try:
        _verify_content_hash(plan, "training plan")
        try:
            data_root = Path(str(plan["data_root"])).resolve(strict=True)
        except (KeyError, OSError) as error:
            raise ControlledBaselineTrainingError(
                f"unable to resolve planned data root: {error}"
            ) from error
        if not data_root.is_dir():
            raise ControlledBaselineTrainingError(
                "planned data root must remain a directory"
            )
        for path_key, hash_key, context in (
            ("baseline_config", "baseline_config_sha256", "baseline config"),
            ("manifest", "manifest_file_sha256", "temporal manifest"),
            (
                "training_index",
                "training_index_file_sha256",
                "training overlay index",
            ),
            ("resolved_config", "resolved_config_sha256", "resolved config"),
        ):
            path = Path(str(plan[path_key])).resolve(strict=True)
            expected = _sha256(plan.get(hash_key), f"plan.{hash_key}")
            if _sha256_file(path, context) != expected:
                raise ControlledBaselineTrainingError(
                    f"{context} changed after the training plan was generated"
                )
        _verify_planned_overlay(plan, prefix="transport")
        _verify_planned_overlay(plan, prefix="fault")

        try:
            from mmengine import Config
            from mmengine.runner import Runner

            from transvision import register_all_modules
        except ImportError as error:
            raise ControlledBaselineTrainingError(
                "training requires the locked MMEngine/MMDet3D runtime"
            ) from error

        register_all_modules()
        config = Config.fromfile(str(plan["resolved_config"]))
        runner = Runner.from_cfg(config)
        return runner.train()
    except _EvaluationError as error:
        raise ControlledBaselineTrainingError(str(error)) from error
    except (KeyError, OSError) as error:
        raise ControlledBaselineTrainingError(
            f"invalid training plan: {error}"
        ) from error


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Train an adapted cooperative baseline against the sealed "
            "DAIR-V2X training overlays."
        )
    )
    parser.add_argument("--baseline", required=True, choices=BASELINES)
    parser.add_argument(
        "--training-index",
        type=Path,
        default=DEFAULT_TRAINING_INDEX,
    )
    parser.add_argument("--work-dir", required=True, type=Path)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--resume", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        plan = build_training_plan(
            baseline=args.baseline,
            training_index=args.training_index,
            work_dir=args.work_dir,
            seed=args.seed,
            resume=args.resume,
        )
        if args.dry_run:
            print(json.dumps({"dry_run": True, **plan}, sort_keys=True))
            return 0
        execute_training_plan(plan)
        print(
            json.dumps(
                {
                    "dry_run": False,
                    "baseline": plan["baseline"],
                    "work_dir": plan["work_dir"],
                    "training_plan": plan["plan_path"],
                },
                sort_keys=True,
            )
        )
        return 0
    except (ControlledBaselineTrainingError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = (
    "BASELINES",
    "BASELINE_CONFIGS",
    "DEFAULT_SEED",
    "DEFAULT_TRAINING_INDEX",
    "ControlledBaselineTrainingError",
    "build_training_plan",
    "execute_training_plan",
    "main",
    "parse_args",
)
